apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-sms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: sms
    spec:
      containers:
      - name: fe-sms
        image: fernandoe/fe-sms-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: 'server.settings.docker'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fe-sms
                key: database_url
          - name: AWS_DEFAULT_REGION
            value: us-west-2
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fe-sms
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fe-sms
                key: AWS_SECRET_ACCESS_KEY
