# Generated by Django 2.0.4 on 2018-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe_sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsmensagem',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('enviado', 'Enviado')], default='criado', max_length=10),
        ),
    ]
